[tool.poetry]
package-mode = false
name = "JoystickGremlin"
version = "16.0r"
description = "A tool for configuring and managing joystick devices."
authors = ["WhiteMagic <white.magic@gmx.de>"]
license = "GPL-3.0-only"
readme = "README.md"
homepage = "https://whitemagic.github.io/JoystickGremlin/"
repository = "https://github.com/WhiteMagic/JoystickGremlin"

[tool.poetry.dependencies]
python = ">=3.14, <3.15"
jsonschema = ">=4.26"
miniaudio = ">=1.71"
PySide6 = ">=6.11.2"
PyInstaller = ">=6.22"
pywin32 = ">=312"
pytest = ">=9.1"
pytest-qt = ">=4.5.0"
pytest-rerunfailures = ">=16.6"
ruff = "^0.16.8"
pyright = "^1.1.414"

[tool.pytest.ini_options]
pythonpath = "."
addopts = "--import-mode=importlib"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py313"
extend-exclude = ["gremlin/user_scripts/", "generate_wix.py", "resources.py", "dist", "doc"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint]
extend-select = ["ANN", "I", "E501"]
ignore = ["B006", "PLW0602", "RUF017", "TRY401", "SIM115"]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["PySide6.QtCore.QModelIndex"]

[tool.pyright]
include = ["action_plugins", "dill", "gremlin", "joystick_gremlin.py", "vjoy"]
exclude = ["**/__pycache__", "**/.git", "**/.venv", "**/venv"]
reportMissingImports = true
reportMissingTypeStubs = false
pythonVersion = "3.14"
pythonPlatform = "Windows"
typeCheckingMode = "basic"
