name: Full build for CI/CD

#on: 'push'

#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

on:
  - push

  release:
    types: [created]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout source
      uses: actions/checkout@master

    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
        architecture: 'x86'

    - name: Use PIP cache if possible
      uses: actions/cache@v1
      if: startsWith(runner.os, 'Windows')
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable
      run: pyinstaller -y --clean joystick_gremlin.spec

    - name: Generate WiX file
      run: |
        python generate_wix.py
        Copy-Item -force joystick_gremlin.wxs dist\joystick_gremlin.wxs

    - name: Candle
      working-directory: dist
      run: '&"$($env:WIX)\bin\candle.exe" joystick_gremlin.wxs'
    
    - name: Light
      working-directory: dist
      run: '&"$($env:WIX)\bin\light.exe" -ext WixUiExtension joystick_gremlin.wixobj'

    - name: Upload artifact
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v1
      with:
        name: joystick_gremlin.msi
        path: dist/joystick_gremlin.msi
    
    - name: Upload release files
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.GITHUB_REF }}
        asset_path: dist/joystick_gremlin.msi
        asset_name: joystick_gremlin.msi
        asset_content_type: application/octet-stream