name: Deploy

on: 'push'
#  push:
#    branches: [ master ]

#  pull_request:
#    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: windows-2019

    steps:
    - name: Checkout source
      uses: actions/checkout@master

    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
        architecture: 'x86'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable
      run: pyinstaller -y --clean joystick_gremlin.spec

    - name: Generate WiX file
      run: |
        python generate_wix.py
        Copy-Item -force joystick_gremlin.wxs dist\joystick_gremlin.wxs

    - name: Pre-build cleanup for WiX
      run: |
        cd dist
        Get-ChildItem -Include PFiles | Remove-Item -Recurse
        Get-ChildItem -Include joystick_gremlin.wixobj | Remove-Item
        Get-ChildItem -Include joystick_gremlin.wixpdb | Remove-Item
        Get-ChildItem -Include joystick_gremlin.msi | Remove-Item

    - name: Candle
      run: '&"$($env:WIX)\bin\candle.exe" joystick_gremlin.wxs'
    
    - name: Light
      run: '&"$($env:WIX)\bin\light.exe" -ext WixUiExtension joystick_gremlin.wixobj'

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: joystick_gremlin.msi
        path: dist/joystick_gremlin.msi