name: NightlyBuild

on:
  push:
    branches:
      - "nightly-build-action"
  # schedule:
  #   - cron: '45 23 * * *' # runs daily at 23:45

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        poetry-version: ["latest"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up poetry for dependency management
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Install the project dependencies with poetry
      run: poetry install
    - name: Build executable
      run: poetry run pyinstaller -y --clean joystick_gremlin.spec
    # - name: Store current date
    #   id: current_date
    #   run: echo "CURRENT_DATE=$(date +'%Y_%m_%d')" >> "$GITHUB_OUTPUT"
    - name: Store current date
      run: |
        $CURRENT_DATE=& Get-Date -format yyyy_MM_dd
        echo "CURRENT_DATE=$CURRENT_DATE" >> $env:GITHUB_ENV
    - name: Echo current date
      run: |
        echo "${{env.CURRENT_DATE}}"
    - name: Upload build
      # env:
      #   CURRENT_DATE: ${{ steps.current_date.outputs.CURRENT_DATE }}
      uses: actions/upload-artifact@v4
      with:
        name: joystick_gremlin_nightly
        path: dist/
        if-no-files-found: warn
        retention-days: 7
        overwrite: true
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        path: /tmp/
    - name: Upload to Nightly release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: Nightly
        files: /tmp/*
        token: ${{ secrets.GITHUB_TOKEN }}
