name: NightlyBuild

on:
  push:
    branches:
      - "nightly-build-action"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        poetry-version: ["latest"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up poetry for dependency management
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Install the project dependencies with poetry
      run: poetry install
    - name: Build executable
      run: poetry run pyinstaller -y --clean joystick_gremlin.spec
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: joystick_gremlin_nightly_${{ steps.date.outputs.date }}
        path: dist/
        if-no-files-found: warn
        retention-days: 7
        overwrite: true
