name: Publish release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: windows-2019

    steps:
    - name: Checkout source
      uses: actions/checkout@master

    - name: Diagnostic
      run: |
        Write-Host "GITHUB_REF: $($env:GITHUB_REF)"

    - name: Get upload URL
      env:
        REPO: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $release = Invoke-RestMethod -Uri "https://api.github.com/repos/$($env:REPO)/releases/tags/$($env:GITHUB_REF.Split('/') |? {![string]::IsNullOrWhitespace($_)} | Select -Last 1)" -Headers @{'Authorization' = 'Bearer $($env:GITHUB_TOKEN)'}
        Write-Host "upload_url = $($release.upload_url)"
        $env:UPLOAD_URL = $release.upload_url

    - name: Diagnostic
      run: |
        Write-Host $env:UPLOAD_URL

    - name: Upload release files
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.GITHUB_REF }}
        asset_path: dist/joystick_gremlin.msi
        asset_name: joystick_gremlin.msi
        asset_content_type: application/octet-stream