name: Publish release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: windows-2019

    steps:
    - name: Checkout source
      uses: actions/checkout@master

    - name: Diagnostic
      run: |
        Write-Host "GITHUB_REF: $($env:GITHUB_REF)"

    - name: Get upload URL
      id: get_upload_url
      env:
        REPO: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $release = Invoke-RestMethod -Uri "https://api.github.com/repos/$($env:REPO)/releases/tags/$($env:GITHUB_REF.Split('/') |? {![string]::IsNullOrWhitespace($_)} | Select -Last 1)" -Headers @{"Authorization" = "Bearer $($env:GITHUB_TOKEN)"}
        Write-Host "upload_url = $($release.upload_url)"
        Write-Output "::set-output name=url::$($release.upload_url)"

    - name: Diagnostic
      run: |
        Write-Host ${{ steps.get_upload_url.outputs.url }}

    - name: Upload release files
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_upload_url.outputs.url }}
        asset_path: README.md
        asset_name: README.md
        asset_content_type: text/plain