name: Publish release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: windows-2019

    steps:
    - name: Checkout source
      uses: actions/checkout@master

    - name: Diagnostic
      env:
        OBJREF: ${{ github.ref }}
      run: |
        Write-Host "GITHUB_REF: $($env:GITHUB_REF)"
        Write-Host "github.ref: $($env:OBJREF)"

    - name: Upload release files
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.GITHUB_REF }}
        asset_path: dist/joystick_gremlin.msi
        asset_name: joystick_gremlin.msi
        asset_content_type: application/octet-stream